/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

fun main() {
    val suma = Suma()
    val resta = Resta()
    val seno = Seno()

    println("Suma: ${suma.ejecutar(2.0, 3.0, 4.0)}")
    println("Resta: ${resta.ejecutar(10.0, 3.0, 2.0)}")
    println("Sen(π/4): ${seno.ejecutar(kotlin.math.PI / 4)}")
}
