/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // ✨ CONFIGURACIÓN JAVA-FX: Añadir el plugin de JavaFX
    // Este plugin es esencial para configurar las dependencias y los argumentos de la VM.
    id("org.openjfx.javafxplugin") version "0.1.0" // Asegúrate de usar la versión estable más reciente
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Las dependencias de JavaFX (como javafx.controls) se añadirán automáticamente
    // gracias al plugin y la configuración 'javafx { ... }'.
}

// ✨ CONFIGURACIÓN JAVA-FX: Define la versión y los módulos a usar.
javafx {
    // Usamos Java 21, así que la versión de JavaFX debe ser compatible.
    version = "21"
    // Módulos necesarios para crear la ventana y usar controles básicos.
    modules("javafx.controls", "javafx.fxml")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define la clase principal para la aplicación. Cambiamos al punto de entrada de JavaFX.
    // Asumimos que la clase JavaFX se llama 'AppFX.kt' en el paquete org.example
    mainClass = "org.example.AppFX" // Cambiado de AppKt a AppFX
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
